apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: redis
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 18.2.0
    helm:
      valuesObject:
        fullnameOverride: redis
        auth:
          enabled: true
          sentinel: false
        master:
          count: 1
          persistence:
            size: 8Gi
        replica:
          replicaCount: 2
          persistence:
            size: 8Gi
        metrics:
          enabled: true
  destination:
    namespace: redis
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
